# CodeGreen Terminal Demo - Fine-Grained Energy Profiling

Output test.mp4
Output test.gif

Require echo

# Authentic terminal with Darkside theme
Set Shell "bash"
Set FontSize 16
Set Width 1400
Set Height 900
Set Padding 30
Set Theme "Darkside"
Set Framerate 60
Set PlaybackSpeed 1
Set TypingSpeed 20ms
Set Margin 10
Set MarginFill "#4dae50"
Set BorderRadius 10
Set WindowBar Colorful



# Start with a clean slate and show the banner instantly
Hide
Type "clear && ./print_banner.sh"
Enter
Show
Sleep 2s